name: Rust-Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd caco3_sh && cargo build --verbose
    - name: Upload Artifacts
      run: cd caco3_sh/target/ && zip -r bin-linux.zip /debug/
    - uses: actions/upload-artifact@v7
      with: 
        path: bin-linux.zip
        archive: false
    - name: Run tests
      run: cd caco3_sh && cargo test --verbose
